# Generated by Django 5.2 on 2025-04-27 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriber", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                (
                    "zip_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("county_fips", models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="phone",
        ),
        migrations.AddField(
            model_name="subscriber",
            name="phone_number",
            field=models.CharField(default="-", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="zip_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subscriber.zipcode"
            ),
        ),
    ]
