# Generated by Django 5.2 on 2025-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriber", "0002_zipcode_remove_subscriber_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=255)),
                ("headline", models.TextField()),
                ("description", models.TextField()),
                ("instruction", models.TextField(blank=True, null=True)),
                ("fips_code", models.CharField(max_length=10)),
                ("urgency", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
